/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 email.gltf --transform
Author: stPixel (https://sketchfab.com/innasparrow)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/3d-icons-email-dfe7298e6c4f4a0385fc2b42104ddaa4
Title: 3D icons / Email
*/

import React, { useRef } from "react";
import { Stage, useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Material } from "three";
import { useFrame } from "react-three-fiber";

type GLTFResult = GLTF & {
  nodes: {
    open_letter_open_letter_0: any;
  };
  materials: {
    material: Material | Material[] | undefined;
    open_letter: Material | Material[] | undefined;
  };
};

export default function Model(props: any) {
  const { nodes, materials } = useGLTF("/email-transformed.glb") as GLTFResult;
  const mesh = useRef<any>(null);

  // Rotate mesh every frame, this is outside of React without overhead
  useFrame(() => {
    mesh.current.rotation.y += 0.01;
  });

  return (
    <Stage environment="city" intensity={0.6} shadows={false}>
      <group {...props} dispose={null} ref={mesh}>
        <mesh
          geometry={nodes.open_letter_open_letter_0.geometry}
          material={materials.open_letter}
          position={[0, 0, 0]}
        />
      </group>
    </Stage>
  );
}

useGLTF.preload("/email-transformed.glb");
